### ISSUE TITLE
Integrate New JSON Schema Generation Tests to Main Testing Harness

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema-xslt#25]
# User Story:

As a Metaschema developer, in order to ensure I can properly test the current and future changes to Metaschema XSLT-M4 implementation's JSON Schema generation use case, I want newer tests integrated into the body of existing tests and I can run them in a consistent way.

## Goals:

This is a tech-debt item from usnistgov/metaschema#240 as requested during review of the related code change is usnistgov/metaschema#253. We have to keep the following goals in mind:

- [ ] SPIKE: Research different avenues to integrate or adopt the new XSpec tests and the current harness; this will require some quick spike work to find options and pick
- [ ] Integrate new tests in usnistgov/metaschema#253 into current test harness (here [in `develop` at current commit](https://github.com/usnistgov/metaschema/blob/f18f72f03176a0b8182dcc18fc10f5d10640849d/test-suite/schema-generation/run-tests.sh))
- [ ] Ensure the updated tests in addition to usnistgov/metaschema#253, also will do schema validation against a JSON document instance for each of the five Metaschemas (this is not currently covered in the XSpec tests, and is likely also not possible)
- [ ] Update the test runner to properly execute locally
- [ ] Ensure it is configured to run in CI/CD

## Dependencies:

- [x] usnistgov/metaschema#253 is successfully reviewed and merged.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
I was reviewing the NIST OSCAL Workboard and realized this escaped my review last week. I will be removing this from the OSCAL workboard and work with @david-waltermire-nist and Metaschema developers to track it in their work stream on the board once they have it set up.

**Comment by aj-stein-nist** [comment]
Per comments in https://github.com/usnistgov/metaschema-xslt/issues/22, A.J. wants to close that issue out and work on testing enhancements in the context of future work in this issue. He will even review the comments here and be sure to include once he pulls this work into his upcoming queue o'stuff. :-)
