### ISSUE TITLE
Complete Pub Checklist and register in MIDAS

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema-xslt#4]
# User Story:

As a user and developer interested in Metaschema implementations, I am concerned to have project policies spelled out regarding not only usage requirements and restrictions, but also implementation strategy and maintenance, so I can plan accordingly.

From a project point of view this entails finalizing the publication checklist and associated policies, and listing (registering) in NIST's metadata systems (MIDAS) as appropriate.

## Goals:

The publication checklist outlines policies respecting publication (access) and ongoing maintenance of this project, This checklist must be complete before the project can be reviewed for formal publication as a research effort and demonstration. Appropriate listings for the project in MIDAS (NIST internal metadata management system) are included among those requirements.

The publication checklist must be completed, which means aligning policies, followed up by creating a record or records in MIDAS and securing approval for them (along with the checklist and everything else).

## Dependencies:

Behind PR #3 is a draft publication checklist (in docs folder). This effort can be worked in that PR until it is merged.

## Acceptance Criteria

- [ ] The publication checklist is completed and approved.
- [ ] Any and all appropriate MIDAS records have been created *and approved* (published) for this project.
- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated.
- [ ] As appropriate, a Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
Note: Citation in readme to be updated with the DOI from MIDAS once we have one.
